version: "3.7"

services:

  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
      - "4575:4575"
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=sqs,sns